<?php
//------------------------------------------------------------------------------
// <generated-code>
//    This code generated by IEntity-Generator 
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </generated-code>
//------------------------------------------------------------------------------

namespace Cimply\App\Models\CimplyWork 
{
    use \Cimply\Interfaces\IBasics;

    abstract class CityModel implements IBasics
    {
        public $infoMessage = array();
        public $saveAble = true;
        public $refresh = false;        
                
        protected $ID;        
        protected $Name;        
        protected $CountryCode;        
        protected $District;        
        protected $Population;        
    }
        
    class CityEntity extends CityModel
    {
        use \Properties, \Cast;              
        
        //Constructor    
        public function __construct($cityModel = null) {
            if(!(is_array($cityModel))) {
                $value = $cityModel;
            } else {
                $value = \Lists::ObjectList($cityModel);
            }
            if(isset($value->message)) {
                $this->infoMessage = $value->message; 
            }
                                
            isset($value->ID) ? settype($value->ID, 'int') ? $this->ID = $value->ID : $this->infoMessage['ID'] = 'wrong datatype "int"' : null;                                  
            isset($value->Name) ? settype($value->Name, 'string') ? $this->Name = $value->Name : $this->infoMessage['Name'] = 'wrong datatype "string"' : null;                                  
            isset($value->CountryCode) ? settype($value->CountryCode, 'string') ? $this->CountryCode = $value->CountryCode : $this->infoMessage['CountryCode'] = 'wrong datatype "string"' : null;                                  
            isset($value->District) ? settype($value->District, 'string') ? $this->District = $value->District : $this->infoMessage['District'] = 'wrong datatype "string"' : null;                                  
            isset($value->Population) ? settype($value->Population, 'string') ? $this->Population = $value->Population : $this->infoMessage['Population'] = 'wrong datatype "string"' : null;              
        }

        /**
         * Summary of Cast
         * @param mixed $mainObject
         * @param mixed $selfObject
         * @return mixed
         */
        final static function Cast($mainObject, $selfObject = self::class): self {
            return self::Cull($mainObject, $selfObject);
        }
        
        public function CalculateStorable() {
            return $this->saveAble;
        }
        
        public function Epilogue() {
            return false;
        }

        public function Prologue() {
            return false;
        }

        function Execute() {
            return $this;
        }

    }
}