<?php
//------------------------------------------------------------------------------
// <generated-code>
//    This code generated by IEntity-Generator 
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </generated-code>
//------------------------------------------------------------------------------

namespace Cimply\App\Models\CimplyWork 
{
    use \Cimply\Interfaces\IBasics;

    abstract class ProcessModel implements IBasics
    {
        public $infoMessage = array();
        public $saveAble = true;
        public $refresh = false;        
                
        protected $process_id;        
        protected $process_name;        
        protected $process_link;        
    }
        
    class ProcessEntity extends ProcessModel
    {
        use \Properties, \Cast;              
        
        //Constructor    
        public function __construct($processModel = null) {
            if(!(is_array($processModel))) {
                $value = $processModel;
            } else {
                $value = \Lists::ObjectList($processModel);
            }
            if(isset($value->message)) {
                $this->infoMessage = $value->message; 
            }
                                
            isset($value->process_id) ? settype($value->process_id, 'int') ? $this->process_id = $value->process_id : $this->infoMessage['process_id'] = 'wrong datatype "int"' : null;                                  
            isset($value->process_name) ? settype($value->process_name, 'string') ? $this->process_name = $value->process_name : $this->infoMessage['process_name'] = 'wrong datatype "string"' : null;                                  
            isset($value->process_link) ? settype($value->process_link, 'string') ? $this->process_link = $value->process_link : $this->infoMessage['process_link'] = 'wrong datatype "string"' : null;              
        }

        /**
         * Summary of Cast
         * @param mixed $mainObject
         * @param mixed $selfObject
         * @return mixed
         */
        final static function Cast($mainObject, $selfObject = self::class): self {
            return self::Cull($mainObject, $selfObject);
        }
        
        public function CalculateStorable() {
            return $this->saveAble;
        }
        
        public function Epilogue() {
            return false;
        }

        public function Prologue() {
            return false;
        }

        function Execute() {
            return $this;
        }

    }
}